//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public string patient_name { get; set; }
        public string patient_email { get; set; }
        public string patient_phone { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<System.DateTime> appoint_date { get; set; }
        public Nullable<System.DateTime> appoint_hour { get; set; }
    
        public virtual Appointment Appointment1 { get; set; }
        public virtual Appointment Appointment2 { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
