//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dental_clinic_details
    {
        public int id { get; set; }
        public string clinic_name { get; set; }
        public string clinic_about { get; set; }
        public string clinic_slogan { get; set; }
        public string clinic_phone { get; set; }
        public string clinic_email { get; set; }
        public string clinic_address { get; set; }
        public string clinic_history { get; set; }
        public string clinic_ceo_name { get; set; }
        public Nullable<System.DateTime> clinic_open_date { get; set; }
    }
}
