//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Awards = new HashSet<Award>();
            this.Leaves = new HashSet<Leave>();
        }
    
        public int id { get; set; }
        public string doctor_fullname { get; set; }
        public string doctor_about { get; set; }
        public string doctor_photo { get; set; }
        public string doctor_phone { get; set; }
        public string doctor_address { get; set; }
        public string doctor_email { get; set; }
        public Nullable<int> doctor_depart_id { get; set; }
        public string doctor_education_file { get; set; }
        public Nullable<int> doctor_salary { get; set; }
        public Nullable<int> doctor_marrige_status_id { get; set; }
        public Nullable<System.DateTime> doctor_begin_time { get; set; }
        public Nullable<System.DateTime> doctor_start_time { get; set; }
        public Nullable<System.DateTime> doctor_start_date { get; set; }
        public Nullable<System.DateTime> doctor_date_of_birth { get; set; }
        public Nullable<int> doctor_gender_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Award> Awards { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MarrigeStatu MarrigeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
    }
}
