//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Attendence
    {
        public int id { get; set; }
        public string stuff_fullname { get; set; }
        public Nullable<int> stuff_gender_id { get; set; }
        public Nullable<int> stuff_marriage_status_id { get; set; }
        public Nullable<int> stuff_salary { get; set; }
        public string stuff_phone { get; set; }
        public string stuff_address { get; set; }
        public string stuff_mail { get; set; }
        public string stuff_photo { get; set; }
        public Nullable<System.DateTime> stuff_start_date { get; set; }
        public Nullable<System.DateTime> stuff_begin_time { get; set; }
        public Nullable<System.DateTime> stuff_end_time { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MarrigeStatu MarrigeStatu { get; set; }
    }
}
