//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string patient_fullname { get; set; }
        public Nullable<int> patient_gender_id { get; set; }
        public Nullable<int> patient_marriage_status_id { get; set; }
        public string patient_phone { get; set; }
        public string patient_address { get; set; }
        public string patient_email { get; set; }
        public Nullable<int> patient_payment { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MarrigeStatu MarrigeStatu { get; set; }
    }
}
