//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff_Atendes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stuff_Atendes()
        {
            this.Stuff_Atendes1 = new HashSet<Stuff_Atendes>();
        }
    
        public int id { get; set; }
        public Nullable<bool> doctor_status { get; set; }
        public Nullable<int> doctor_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stuff_Atendes> Stuff_Atendes1 { get; set; }
        public virtual Stuff_Atendes Stuff_Atendes2 { get; set; }
    }
}
