//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Roles
    {
        public int id { get; set; }
        [DisplayName("User Name")]
        public string user_role_name { get; set; }
        public string user_role_mail { get; set; }
        public string user_role_password { get; set; }
       public string LoginErrorMessage { get; set; }
    }
}
